# Generated by Django 4.2.5 on 2023-10-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer_details',
        ),
    ]
