# Generated by Django 4.2.5 on 2023-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_applied_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_resume',
            field=models.FileField(default='', upload_to='applicant/resume'),
        ),
    ]
