# Generated by Django 4.2.5 on 2023-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applied_jobs_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_resume',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
