# Generated by Django 4.2.5 on 2023-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_alter_applied_jobs_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='applicant_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='applicant_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
