# Generated by Django 4.2.5 on 2023-10-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_applied_jobs_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
