# Generated by Django 4.2.5 on 2023-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_remove_applied_jobs_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='Applied_id',
            field=models.IntegerField(default=0),
        ),
    ]
