# Generated by Django 4.2.5 on 2024-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_applied_jobs_applied_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='company_name',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_coverletter',
            field=models.CharField(default='0000000', max_length=2000),
        ),
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_resume',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='resume/'),
        ),
    ]
