# Generated by Django 4.2.5 on 2024-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_applied_jobs_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='applicant_resume',
            field=models.FileField(default='', upload_to='resume/'),
        ),
    ]
