# Generated by Django 4.2.5 on 2023-10-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant_details',
        ),
        migrations.DeleteModel(
            name='Employer_details',
        ),
    ]
