# Generated by Django 4.2.5 on 2023-10-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('employer_no', models.IntegerField(default=0)),
                ('employer_email', models.EmailField(max_length=254)),
                ('employer_age', models.BigIntegerField(default=0)),
                ('employer_address', models.CharField(max_length=400)),
                ('employer_gender', models.CharField(max_length=15)),
            ],
        ),
    ]
