# Generated by Django 4.2.5 on 2023-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_desc', models.CharField(max_length=400)),
                ('company_location', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=400)),
                ('job_desc', models.CharField(max_length=400)),
                ('salary', models.IntegerField(default=0)),
                ('requied_experience', models.IntegerField(default=0)),
                ('post_date', models.DateField()),
                ('application_last_day', models.DateField()),
                ('skill_required', models.CharField(max_length=200)),
                ('dis_type', models.CharField(max_length=100)),
            ],
        ),
    ]
